### ISSUE TITLE
Selectors for buttons added to myOverView never get called?

### ISSUE THREAD

**Issue by DiamondGeezer** [matteogobbi/MGSpotyViewController#10]
Selectors for buttons added to myOverView never get called? Could you please provide an example button?

```
UIButton *twitterButton = [UIButton buttonWithType:UIButtonTypeCustom];
[twitterButton setTitle:twitterString forState:UIControlStateNormal];
[twitterButton addTarget:self action:@selector(hello:) forControlEvents:UIControlEventTouchUpInside];
twitterButton.frame = CGRectMake(50, 50, twitterLabelSize.width, 30.0);
[twitterButton setBackgroundColor:[UIColor clearColor]];
[twitterButton setTitleColor:[UIColor whiteColor] forState:UIControlStateNormal];
[twitterButton setTitleShadowColor:[UIColor lightGrayColor] forState:UIControlStateNormal];
[twitterButton setTitleEdgeInsets:UIEdgeInsetsMake( -4.0f, 0.0f, 0.0f, 0.0f)];
[[twitterButton titleLabel] setShadowOffset:CGSizeMake( 0.0f, 0.5f)];
[[twitterButton titleLabel] setFont:[UIFont fontWithName:@"Avenir-Medium" size:14.0f]];
[[twitterButton titleLabel] setMinimumScaleFactor:0.8f];
[[twitterButton titleLabel] setAdjustsFontSizeToFitWidth:YES];
[[twitterButton titleLabel] setTextAlignment:NSTextAlignmentLeft];
[twitterButton setSelected:NO];
twitterButton.userInteractionEnabled = YES;
[twitterButton setClipsToBounds:YES];
[view addSubview:twitterButton];

- (void) hello:(id) sender  { 
    NSLog(@"helloooo"); 
}
```

**Comment by eak65** [comment]
I am having the same problem. I used your example:


    - (UIView *)myOverView {
    UIView *view = [[UIView alloc] initWithFrame:self.overView.bounds];
    self.overView.userInteractionEnabled=YES;
    //Add an example imageView
    UIImageView *imageView = [[UIImageView alloc] initWithFrame:CGRectMake(view.center.x-50.0, view.center.y-60.0, 100.0, 100.0)];

    [imageView setContentMode:UIViewContentModeScaleAspectFill];
    [imageView setClipsToBounds:YES];
    [imageView.layer setBorderColor:[UIColor whiteColor].CGColor];
    [imageView.layer setBorderWidth:2.0];
    [imageView.layer setCornerRadius:imageView.frame.size.width/2.0];
    imageView.image =    [UIImage imageWithData:[NSData dataWithContentsOfURL:[NSURL URLWithString:[DataManager shared].myself.profileImageUrl]]];
    imageView.userInteractionEnabled=YES;
    imageView.multipleTouchEnabled=YES;
    UITapGestureRecognizer *oneTouch=[[UITapGestureRecognizer alloc]initWithTarget:self action:@selector(OneTouchHandeler)];
    
    [oneTouch setNumberOfTouchesRequired:1];
    
    [imageView addGestureRecognizer:oneTouch];
    
    //Add an example label
    UILabel *lblTitle = [[UILabel alloc] initWithFrame:CGRectMake(view.center.x-120.0, view.center.y+50.0, 240.0, 50.0)];
    [lblTitle setText:[DataManager shared].myself.firstName];
    [lblTitle setFont:[UIFont boldSystemFontOfSize:25.0]];
    [lblTitle setTextAlignment:NSTextAlignmentCenter];
    [lblTitle setTextColor:[UIColor whiteColor]];
    
    view.userInteractionEnabled=YES;
    [view addSubview:imageView];
    [view addSubview:lblTitle];

    return view;
    }

    -(void)OneTouchHandeler
    {
    // never called
    }


I am trying to get the image to do stuff when it is touched.  The selector is never called however.

**Comment by matteogobbi** [comment]
Hi guys, I just found the time to solve this issue. A new pod version has been created. Just update and enjoy ;)
