### ISSUE TITLE
App crashing on memory warnings

### ISSUE THREAD

**Issue by SolomonBier** [matteogobbi/MGSpotyViewController#11]
I'm downloading pictures from Amazon S3 and setting the main image view via the setMainImage method. This works fine, but when scrolling the app crashes with a memory warning. 

Is there a size constraint I should abide by ?

**Comment by SolomonBier** [comment]
Fixed the above with the following code. May be worth adding to the setImageView method:

            // Resize Image
            CGSize size=CGSizeMake(self.mainImageView.frame.size.width,self.mainImageView.frame.size.height);
            UIGraphicsBeginImageContext(size);
            [tempImage drawInRect:CGRectMake(0, 0, size.width, size.height)];
            UIImage *scaledImage = UIGraphicsGetImageFromCurrentImageContext();
            UIGraphicsEndImageContext();
            //End Resize Image
            
            [self setMainImage:scaledImage];

**Comment by matteogobbi** [comment]
Hi,
If you think to have fixed an issue, please submit a pull request. 

Thank you.

**Comment by SolomonBier** [comment]
Submitted pull request. This address may also address the other memory warning you previously closed.

Great work, love this VC!

Cheers
