### ISSUE TITLE
Tap events on image view to edit image

### ISSUE THREAD

**Issue by shahankit** [matteogobbi/MGSpotyViewController#14]
I'm trying to add tapgesturerecognizer on imageView inside the overview and add a selector event similar to contact button. But it's not working.

**Comment by matteogobbi** [comment]
Do you have the last version?

**Comment by shahankit** [comment]
Yeah cloned yesterday. I found the hitTest code in MGSpotyView but that helps only for button like Contact button in demo, but I think tap events are not forwarded to _overView and imageView can only have tap gesture.

**Comment by matteogobbi** [comment]
I will have a look this night or next days.

**Comment by shahankit** [comment]
Ok thanks.

**Comment by matteogobbi** [comment]
Hi @shahankit I just tested and everything works.

I think to have figured out what is your problem. Did you do:
`imageView.userInteractionEnabled = YES;` ?

An `UIImage` of default has the interaction disabled. So you should activate it ;)

I just pushed the demo project with the working tap recognizer ;)

Enjoy!

**Comment by shahankit** [comment]
Oops missed that detail. Thanks.
