### ISSUE TITLE
Which blur effect does this view controller use?

### ISSUE THREAD

**Issue by chenweiyj** [matteogobbi/MGSpotyViewController#16]
Is it Guassian Blur or Background Blur?

**Comment by aayushranaut** [comment]
It uses Guassian blur.
Check out [MGViewController.m](https://github.com/matteogobbi/MGSpotyViewController/blob/master/MGSpotyViewController/ImageEffects/UIImageView%2BLBBlurredImage.m)
```objective-c
- (void)setImageToBlur:(UIImage *)image
            blurRadius:(CGFloat)blurRadius
       completionBlock:(LBBlurredImageCompletionBlock) completion
```
