### ISSUE TITLE
custom initializer

### ISSUE THREAD

**Issue by alizx** [matteogobbi/MGSpotyViewController#17]
Hi 
it would be better not to use custom initializer for viewController because when sb use seque it just only calls the default initializer method

**Comment by matteogobbi** [comment]
That is the reason why I hate storyboard.

;)

On Sunday, 10 May 2015, alizx <notifications@github.com> wrote:

> Hi
> it would be better not to use custom initializer for viewController
> because when sb use seque it just only calls the default initializer method
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/matteogobbi/MGSpotyViewController/issues/17>.
>


-- 
*Matteo Gobbi*

**Comment by alizx** [comment]
same here ;) 
but you can make this nice pice of code more usable 
anyway thank you for your answer
