### ISSUE TITLE
Main top image

### ISSUE THREAD

**Issue by shafqat-muneer** [matteogobbi/MGSpotyViewController#26]
Hi,
MGViewController *spotyViewController = [[MGViewController alloc] initWithMainImage:[UIImage imageNamed:@"example"]];

I not want to use image; In my scenario, i have a tableview cell that i want to add at top; Because i also need some interactions on it. Can it be possible in current state of your control? If not then please suggest things to modify in control.

Thanks,

**Comment by matteogobbi** [comment]
Hi man,
I don't really get what you need but you have an header and a bunch of cells in this component, so you should be able to reach any result you need.
