### ISSUE TITLE
Grouped Style

### ISSUE THREAD

**Issue by Hadjimina** [matteogobbi/MGSpotyViewController#28]
Heyo 

Awesome Project !!!
Can I somehow change the TableViewStyle to grouped instead of plain ? Was messing around with the code but didn't get any results.

Cheers
Philipp

**Comment by matteogobbi** [comment]
Hi @Hadjimina,
the component is not thought to support grouped style. It is thought like a tableview container, where you can set transparent cell and apply the design you prefer.
Indeed, to reach out the effect wanted from this component, it's fundamental using the default tableView's style.
