### ISSUE TITLE
Support for UITableViewStyleGrouped and changing mainImage

### ISSUE THREAD

**Issue by insanj** [matteogobbi/MGSpotyViewController#8]
At the moment, ```MGSpotyViewController``` doesn't handle ```UITableViewStyleGrouped``` very well, allowing the backing view to be visible alongside the overView behind the cells (especially when scrolling). Also, there's no way to properly change the ```mainImageView``` image after its initial setup (the image backing is not visible from other classes). This means there's no way to "lazy load" imagery and prevent lengthy delays if the main image needs to be pulled from the server. Love the utility besides these drawbacks! I'm sure they'd be solved by simply using header-declared properties instead of ivars.

Let me know if you have any plans to resolve these issues, or if you wouldn't mind me submitting a pull request for them myself :)

**Comment by matteogobbi** [comment]
Done
